# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.1
_src_path: https://github.com/jupyterlab/extension-template
author_email: gyq673516081@gmail.com
author_name: Yuqiang Gu
has_binder: true
has_settings: false
kind: frontend
labextension_name: jupyterlab_apod
project_short_description: A JupyterLab extension for showing apod.
python_name: jupyterlab_apod
repository: https://github.com/guyq1997/jupyterlab-ext-my
test: true

